[package]
name = "typed_future"
version = "1.0.0"
edition = "2018"
rust-version = "1.31"
license = "Unlicense"
description = "Deanonymize async functions"
keywords = ["async", "macro"]
repository = "https://github.com/noahbadoa/typed_future.git"

[lib]
proc-macro = true

[dependencies]
quote = {version = "1.*"}
syn = {version = "2.*", features = ["full", "extra-traits"]}
proc-macro2 = {version = "1.*"}